---
- name: Install Docker and Start Service
  hosts: all
  become: yes
  tasks:
    - name: Install required dependencies
      dnf:
        name:
          - dnf-plugins-core
        state: present

    - name: Add Docker repository
      command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      when: ansible_distribution == "Amazon Linux"

    - name: Install Docker
      dnf:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
