---
- hosts: all
  become: yes
  tasks:
    - name: Ensure NTP is installed
      dnf:
        name: ntp
        state: present
    - name: Ensure NTPD is running
      service:
        name: ntpd
        state: started
        enabled: yes
