---
- hosts: all
  vars:
    - username: ansible
    - home: /home/ansible
  tasks:
    - name: print variables
      debug:
        msg: 
          - "Username: {{ username }}, Home dir: {{ home }}"
          - "IPv4 address: {{ ansible_default_ipv4.address }}"
