---
- hosts: all
  become: true
  tasks:
    - name: Create a group
      group:
        name: developers
        state: present

    - name: Create a user
      user:
        name: karthik
        group: developers
        password: "{{ 'K21Academy' | password_hash('sha512') }}"
        state: present
